apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: seldon-gateway
spec:
  selector:
    app: ingressgateway
    istio: ingress-gke-system
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP